name: Generate Streak Stats

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - ".github/workflows/streak-stats.yml"
  workflow_dispatch:

concurrency:
  group: "streak-stats"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: "user=HoneyTyagii&theme=tokyonight_duo"
          path: dist/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish streak stats
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: streaks
          force_orphan: true
